### ISSUE TITLE
EdGps.csproj - ProjectSDK

### ISSUE THREAD

**Issue by spreedated** [ComputerMaster1st/EdGPS#6]
The latest `EdGps.csproj` file includes in its first line `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">` -- this leads to the attached error message.
Changing the the line to `<Project Sdk="Microsoft.NET.Sdk">` (which was when on netcoreapp2.2) makes the project loadable again.

![154544](https://user-images.githubusercontent.com/21370839/59726326-783fa300-9231-11e9-9501-2caf6c8709bf.png)

I'm using Visual Studio Enterprise 2017 with .NET Core 3.0.100 preview6

**Comment by ComputerMaster1st** [comment]
Hi There,

NETCore 3 features can only be used via VS2019 sadly. It's stated on Microsoft's download page. ;)

**Comment by spreedated** [comment]
I must have overseen this, my mistake.

I've also encountered some other "things" when I took a look at the code.
`VoicePlayer.cs` uses `System.Windows.Media` for reading and playing MP3s - which namespace is not part of .net core 2.2 - however, reading&playing MP3s could also be achieved by using the `NAudio` package, which would make it compatible for .NET Core 2.2.

In `JournalReader.cs` you're using this syntax:

```
foreach (var journal in journalFiles) {
                using FileStream fs = journal.Open(FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                using StreamReader sr = new StreamReader(fs);
                while (!sr.EndOfStream)
                    ReadEvent(Parser.ParseJson(sr.ReadLine()));
            }
```

I don't know if this is a .NET Core 3.x thing, but the correct one should be:

```
foreach (var journal in journalFiles)
            {
                using (FileStream fs = journal.Open(FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                {
                    using (StreamReader sr = new StreamReader(fs))
                    {
                        while (!sr.EndOfStream)
                            ReadEvent(Parser.ParseJson(sr.ReadLine()));
                    }

                }

            }
```

Also, this code will loop through all the journal entries on startup of the app, which may take some time when the there's plenty of journal logs and may look like unwanted behaviour for a user, since the window flushes the output in a split second for each entry until it ends at the newest one and is ready to go. - This happens only at a fresh startup.

**Comment by spreedated** [comment]
Here is my `VoicePlayer.cs` (**untested**) using `NAudio` for playback:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
//using System.Windows.Media;
using EdGps.Core;
using NAudio.Wave;

namespace EdGps
{
    public class VoicePlayer
    {
        private readonly SemaphoreSlim _lock = new SemaphoreSlim(1);
        private readonly Dictionary<VoiceType, TimeSpan> _mp3Times = new Dictionary<VoiceType, TimeSpan>();

        public async Task Play(VoiceType response) {
            await _lock.WaitAsync();

            var localFilePath = Path.Combine(Directories.VoiceDir, $"{response.ToString()}.mp3");

            if (!_mp3Times.ContainsKey(response))
            {
                using (var mp3File = new Mp3FileReader(Path.Combine(Directories.VoiceDir, $"{response.ToString()}.mp3")))
                {
                   _mp3Times.Add(response, mp3File.TotalTime);
                }
                
            }

            using (var ms = File.OpenRead(Path.GetFullPath(localFilePath)))
            using (var rdr = new Mp3FileReader(ms))
            using (var wavStream = WaveFormatConversionStream.CreatePcmStream(rdr))
            using (var baStream = new BlockAlignReductionStream(wavStream))
            using (var waveOut = new WaveOutEvent())
            {
                waveOut.Init(baStream);
                waveOut.Play();
            }

            //var _wmp = new MediaPlayer();
            //_wmp.Open(new Uri(Path.GetFullPath(localFilePath)));
            //_wmp.Play();

            await Task.Delay(_mp3Times[response]);
            _lock.Release();
        }
    }
}
```

**Comment by ComputerMaster1st** [comment]
Hi There,

The using statements is part of the latest C# version. VS 2019's intellisense did it. As for the voiceplayer changes, if they work, feel free to submit a PR with it. It'll allow for users on linux to perhaps also use it.

As for the journal logs, I'm thinking of moving the "fresh (re)-build" to a background task so it'll allow the GPS to be used while it builds the system directory.

**Comment by spreedated** [comment]
I've made a PR for the `VoicePlayer.cs` code and changed some unnecassry lines from my comment above.

> As for the journal logs, I'm thinking of moving the "fresh (re)-build" to a background task so it'll allow the GPS to be used while it builds the system directory.

That's just what I had in mind, put it back to thread or just in background while a loading message displays for the user.

**Comment by ComputerMaster1st** [comment]
Hi There,

I've gone ahead & merged #8 . I'll add the new star types while I'm at it then I can put out a new build.

**Comment by spreedated** [comment]
Awesome! - If you wanna go back to 2.2 you just need to change the syntax in the `JournalReader.cs` and you're good to go (I could push a PR for this). Feel free to close this issue.

**Comment by ComputerMaster1st** [comment]
Hi There,

Closing issue as requested. :)
